schema_version = 1
id = "caddyfile"
name = "Caddyfile"
version = "0.1.0"
description = "Caddyfile language support for Zed"
authors = ["Matthew Penner <me@matthewp.io>"]
repository = "https://github.com/caddyserver/zed-caddyfile"

[grammars.caddyfile]
repository = "https://github.com/caddyserver/tree-sitter-caddyfile"
rev = "8951716aa2855e02dada302c540a90f277546095"
